start_tags_with_attributes = ["<scr'+'ipt", "<!--", "<!DOCTYPE", "<a", "<abbr", "<acronym", "<address", "<applet", "<area", "<article", "<aside", "<audio", "<b", "<base", "<basefont", "<bdi", "<bdo", "<big", "<blockquote", "<body", "<br", "<button", "<canvas", "<caption", "<center", "<cite", "<code", "<col", "<colgroup", "<datalist", "<dd", "<del", "<details", "<dfn", "<dialog", "<dir", "<div", "<dl", "<dt", "<em", "<embed", "<fieldset", "<figcaption", "<figure", "<font", "<footer", "<form", "<frame", "<frameset", "<h1", "<head", "<header", "<hr", "<html", "<i", "<iframe", "<img", "<input", "<ins", "<kbd", "<label", "<legend", "<li", "<link", "<main", "<map", "<mark", "<menu", "<menuitem", "<meta", "<meter", "<nav", "<noframes", "<noscript", "<object", "<ol", "<optgroup", "<option", "<output", "<p", "<param", "<picture", "<pre", "<progress", "<q", "<rp", "<rt", "<ruby", "<s", "<samp", "<script", "<section", "<select", "<small", "<source", "<span", "<strike", "<strong", "<style", "<sub", "<summary", "<sup", "<table", "<tbody", "<td", "<template", "<textarea", "<tfoot", "<th", "<thead", "<time", "<title", "<tr", "<track", "<tt", "<u", "<ul", "<var",
                              "<video", "<wbr", "<SCR'+'IPT", "<!--", "<!DOCTYPE", "<A", "<ABBR", "<ACRONYM", "<ADDRESS", "<APPLET", "<AREA", "<ARTICLE", "<ASIDE", "<AUDIO", "<B", "<BASE", "<BASEFONT", "<BDI", "<BDO", "<BIG", "<BLOCKQUOTE", "<BODY", "<BR", "<BUTTON", "<CANVAS", "<CAPTION", "<CENTER", "<CITE", "<CODE", "<COL", "<COLGROUP", "<DATALIST", "<DD", "<DEL", "<DETAILS", "<DFN", "<DIALOG", "<DIR", "<DIV", "<DL", "<DT", "<EM", "<EMBED", "<FIELDSET", "<FIGCAPTION", "<FIGURE", "<FONT", "<FOOTER", "<FORM", "<FRAME", "<FRAMESET", "<H1", "<HEAD", "<HEADER", "<HR", "<HTML", "<I", "<IFRAME", "<IMG", "<INPUT", "<INS", "<KBD", "<LABEL", "<LEGEND", "<LI", "<LINK", "<MAIN", "<MAP", "<MARK", "<MENU", "<MENUITEM", "<META", "<METER", "<NAV", "<NOFRAMES", "<NOSCRIPT", "<OBJECT", "<OL", "<OPTGROUP", "<OPTION", "<OUTPUT", "<P", "<PARAM", "<PICTURE", "<PRE", "<PROGRESS", "<Q", "<RP", "<RT", "<RUBY", "<S", "<SAMP", "<SCRIPT", "<SECTION", "<SELECT", "<SMALL", "<SOURCE", "<SPAN", "<STRIKE", "<STRONG", "<STYLE", "<SUB", "<SUMMARY", "<SUP", "<TABLE", "<TBODY", "<TD", "<TEMPLATE", "<TEXTAREA", "<TFOOT", "<TH", "<THEAD", "<TIME", "<TITLE", "<TR", "<TRACK", "<TT", "<U", "<UL", "<VAR", "<VIDEO", "<WBR"]
end_tags = ["</scr'+'ipt>", "</!DOCTYPE>", "</a>", "</abbr>", "</acronym>", "</address>", "</applet>", "</area>", "</article>", "</aside>", "</audio>", "</b>", "</base>", "</basefont>", "</bdi>", "</bdo>", "</big>", "</blockquote>", "</body>", "</br>", "</button>", "</canvas>", "</caption>", "</center>", "</cite>", "</code>", "</col>", "</colgroup>", "</datalist>", "</dd>", "</del>", "</details>", "</dfn>", "</dialog>", "</dir>", "</div>", "</dl>", "</dt>", "</em>", "</embed>", "</fieldset>", "</figcaption>", "</figure>", "</font>", "</footer>", "</form>", "</frame>", "</frameset>", "</h1>", "</head>", "</header>", "</hr>", "</html>", "</i>", "</iframe>", "</img>", "</input>", "</ins>", "</kbd>", "</label>", "</legend>", "</li>", "</link>", "</main>", "</map>", "</mark>", "</menu>", "</menuitem>", "</meta>", "</meter>", "</nav>", "</noframes>", "</noscript>", "</object>", "</ol>", "</optgroup>", "</option>", "</output>", "</p>", "</param>", "</picture>", "</pre>", "</progress>", "</q>", "</rp>", "</rt>", "</ruby>", "</s>", "</samp>", "</script>", "</section>", "</select>", "</small>", "</source>", "</span>", "</strike>", "</strong>", "</style>", "</sub>", "</summary>", "</sup>", "</table>", "</tbody>", "</td>", "</template>", "</textarea>", "</tfoot>", "</th>", "</thead>", "</time>", "</title>", "</tr>", "</track>", "</tt>", "</u>", "</ul>", "</var>", "</video>",
            "</wbr>", "</SCR'+'IPT>", "</!DOCTYPE>", "</A>", "</ABBR>", "</ACRONYM>", "</ADDRESS>", "</APPLET>", "</AREA>", "</ARTICLE>", "</ASIDE>", "</AUDIO>", "</B>", "</BASE>", "</BASEFONT>", "</BDI>", "</BDO>", "</BIG>", "</BLOCKQUOTE>", "</BODY>", "</BR>", "</BUTTON>", "</CANVAS>", "</CAPTION>", "</CENTER>", "</CITE>", "</CODE>", "</COL>", "</COLGROUP>", "</DATALIST>", "</DD>", "</DEL>", "</DETAILS>", "</DFN>", "</DIALOG>", "</DIR>", "</DIV>", "</DL>", "</DT>", "</EM>", "</EMBED>", "</FIELDSET>", "</FIGCAPTION>", "</FIGURE>", "</FONT>", "</FOOTER>", "</FORM>", "</FRAME>", "</FRAMESET>", "</H1>", "</HEAD>", "</HEADER>", "</HR>", "</HTML>", "</I>", "</IFRAME>", "</IMG>", "</INPUT>", "</INS>", "</KBD>", "</LABEL>", "</LEGEND>", "</LI>", "</LINK>", "</MAIN>", "</MAP>", "</MARK>", "</MENU>", "</MENUITEM>", "</META>", "</METER>", "</NAV>", "</NOFRAMES>", "</NOSCRIPT>", "</OBJECT>", "</OL>", "</OPTGROUP>", "</OPTION>", "</OUTPUT>", "</P>", "</PARAM>", "</PICTURE>", "</PRE>", "</PROGRESS>", "</Q>", "</RP>", "</RT>", "</RUBY>", "</S>", "</SAMP>", "</SCRIPT>", "</SECTION>", "</SELECT>", "</SMALL>", "</SOURCE>", "</SPAN>", "</STRIKE>", "</STRONG>", "</STYLE>", "</SUB>", "</SUMMARY>", "</SUP>", "</TABLE>", "</TBODY>", "</TD>", "</TEMPLATE>", "</TEXTAREA>", "</TFOOT>", "</TH>", "</THEAD>", "</TIME>", "</TITLE>", "</TR>", "</TRACK>", "</TT>", "</U>", "</UL>", "</VAR>", "</VIDEO>", "</WBR>"]
start_tags = ["&nbsp;", "<scr'+'ipt>", "<!----!>", "<!DOCTYPE>", "<a>", "<abbr>", "<acronym>", "<address>", "<applet>", "<area>", "<article>", "<aside>", "<audio>", "<b>", "<base>", "<basefont>", "<bdi>", "<bdo>", "<big>", "<blockquote>", "<body>", "<br>", "<button>", "<canvas>", "<caption>", "<center>", "<cite>", "<code>", "<col>", "<colgroup>", "<datalist>", "<dd>", "<del>", "<details>", "<dfn>", "<dialog>", "<dir>", "<div>", "<dl>", "<dt>", "<em>", "<embed>", "<fieldset>", "<figcaption>", "<figure>", "<font>", "<footer>", "<form>", "<frame>", "<frameset>", "<h1>", "<head>", "<header>", "<hr>", "<html>", "<i>", "<iframe>", "<img>", "<input>", "<ins>", "<kbd>", "<label>", "<legend>", "<li>", "<link>", "<main>", "<map>", "<mark>", "<menu>", "<menuitem>", "<meta>", "<meter>", "<nav>", "<noframes>", "<noscript>", "<object>", "<ol>", "<optgroup>", "<option>", "<output>", "<p>", "<param>", "<picture>", "<pre>", "<progress>", "<q>", "<rp>", "<rt>", "<ruby>", "<s>", "<samp>", "<script>", "<section>", "<select>", "<small>", "<source>", "<span>", "<strike>", "<strong>", "<style>", "<sub>", "<summary>", "<sup>", "<table>", "<tbody>", "<td>", "<template>", "<textarea>", "<tfoot>", "<th>", "<thead>", "<time>", "<title>", "<tr>", "<track>", "<tt>", "<u>", "<ul>", "<var>", "<video>",
              "<wbr>", "<SCR'+'IPT>", "<!-->", "<!DOCTYPE>", "<A>", "<ABBR>", "<ACRONYM>", "<ADDRESS>", "<APPLET>", "<AREA>", "<ARTICLE>", "<ASIDE>", "<AUDIO>", "<B>", "<BASE>", "<BASEFONT>", "<BDI>", "<BDO>", "<BIG>", "<BLOCKQUOTE>", "<BODY>", "<BR>", "<BUTTON>", "<CANVAS>", "<CAPTION>", "<CENTER>", "<CITE>", "<CODE>", "<COL>", "<COLGROUP>", "<DATALIST>", "<DD>", "<DEL>", "<DETAILS>", "<DFN>", "<DIALOG>", "<DIR>", "<DIV>", "<DL>", "<DT>", "<EM>", "<EMBED>", "<FIELDSET>", "<FIGCAPTION>", "<FIGURE>", "<FONT>", "<FOOTER>", "<FORM>", "<FRAME>", "<FRAMESET>", "<H1>", "<HEAD>", "<HEADER>", "<HR>", "<HTML>", "<I>", "<IFRAME>", "<IMG>", "<INPUT>", "<INS>", "<KBD>", "<LABEL>", "<LEGEND>", "<LI>", "<LINK>", "<MAIN>", "<MAP>", "<MARK>", "<MENU>", "<MENUITEM>", "<META>", "<METER>", "<NAV>", "<NOFRAMES>", "<NOSCRIPT>", "<OBJECT>", "<OL>", "<OPTGROUP>", "<OPTION>", "<OUTPUT>", "<P>", "<PARAM>", "<PICTURE>", "<PRE>", "<PROGRESS>", "<Q>", "<RP>", "<RT>", "<RUBY>", "<S>", "<SAMP>", "<SCRIPT>", "<SECTION>", "<SELECT>", "<SMALL>", "<SOURCE>", "<SPAN>", "<STRIKE>", "<STRONG>", "<STYLE>", "<SUB>", "<SUMMARY>", "<SUP>", "<TABLE>", "<TBODY>", "<TD>", "<TEMPLATE>", "<TEXTAREA>", "<TFOOT>", "<TH>", "<THEAD>", "<TIME>", "<TITLE>", "<TR>", "<TRACK>", "<TT>", "<U>", "<UL>", "<VAR>", "<VIDEO>", "<WBR>"]



class Query:
    question_tokens = []
    answer1_tokens = []
    answer2_tokens = []

    def __init__(self, question_tokens, answer1_tokens, answer2_tokens):
        self.question_tokens = question_tokens
        self.answer1_tokens = answer1_tokens
        self.answer2_tokens = answer2_tokens

    def get_question_tokens(self):
        return self.question_tokens

    def set_question_tokens(self, tokens):
        self.question_tokens = tokens

    def set_answer_tokens(self, ans_1, ans_2):
        self.answer1_tokens = ans_1
        self.answer2_tokens = ans_2

    def get_answer_tokens(self):
        return (self.answer1_tokens, self.answer2_tokens)